baseURL = "https://keanu73.net"
languageCode = "en-gb"
title = "Keanu"

[menu]
  [[menu.header]]
    name = "mail"
    weight = 0
    url = "/mail"

[params]
  title = "Keanu"
  description = "You have 1 unread message."
  images = ["aiden.png"]
  
  GithubID = "Keanu73"
  Email = "keanu@keanu73.net"
  Name = "Keanu"
  HeaderUsername = "keanu73"
  HeaderHostname = "zion"
  ProfilePicture = "/aiden.png"
  Favicon = "/aiden.png"
