baseURL = "https://keanu73.net"
languageCode = "en-gb"
title = "Keanu C"

[menu]
  [[menu.header]]
    name = "mail"
    weight = 0
    url = "/mail"

[params]
  title = "Keanu C"
  description = "You have 1 unread message."
  images = ["aiden.png"]
  
  GithubID = "Keanu73"
  TwitterID = "Keanu73RBLX"
  RedditID = "Keanu73"
  SteamID = "keanu73"
  Email = "keanu@keanu73.net"
  Name = "Keanu C"
  HeaderUsername = "keanu73"
  HeaderHostname = "zion"
  ProfilePicture = "/aiden.png"
  Favicon = "/aiden.png"
