name: Deploy website to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Hugo build to Github Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository files
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo website
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: keanu73.net
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages