name: Deploy website to server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Hugo build to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository files
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo website
        run: hugo --minify

      - name: Deploy to server
        uses: up9cloud/action-rsync@master
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          KEY: ${{ secrets.KEY }}
          VERBOSE: true
          SOURCE: ./public/
          TARGET: /var/www/html/
          ARGS: -avz -O --delete --exclude=.gitignore --exclude=.github/ --exclude=.git/
